### ISSUE TITLE
SH1106 OLED Support

### ISSUE THREAD

**Issue by erik-l** [notro/fbtft#122]
There is already support for the great SSD1306 OLED 128x64 display.
Chinese manufacturers sell cheap OLED displays all over the internet (especially eBay) which are "SSD1306" compatible but they use the SH1106 driver.

I also bought one of these and got problems running example sketches from Adafruit and U8gLib but quickly found these notes:

https://code.google.com/p/u8glib/issues/detail?id=240

The difference seems just to be very little... just a tweak in adressing.
Maybe you can add this case into your driver and make some people out there really happy.

The display itself seems pretty good to me after changing these parameters and I got some pretty fast framerates on HW SPI.

Thanks and keep up your great work!

**Comment by fiveseven808** [comment]
What ever happened to this? I've noticed that SSD1306 displays are harder to find than SH1106 ones. I'd be happy to contribute to this issue if I knew how! :)  I have a SH1106 display that was incorrectly sold to me as an SSH1306 display. I just verified this using the luma.oled library today. I'd like to use this with fbtft if possible!

**Comment by notro** [comment]
I have stopped working on fbtft now, tinydrm is the new kid on the block: https://github.com/notro/fbtft/wiki/Development

There is this patch that didn't get any response: https://www.spinics.net/lists/linux-driver-devel/msg94620.html
