### ISSUE TITLE
Arch Linux: bcm2708_spi bcm2708_spi.0: couldn't allocate a DMA channel

### ISSUE THREAD

**Issue by notro** [notro/fbtft#142]
moved from #79 

Hi notro,
I'm trying to get a ITDB2.4 working on Arch Linux

SPI module is loaded
spi_bcm2708 8159 0

but the dmesg give

```
[ 4.524340] fbtft_device: SPI devices registered:
[ 10.855402] bcm2708_spi bcm2708_spi.0: couldn't allocate a DMA channel
```

how can I solve that?

thanks
ste

**Comment by mrdolmo** [comment]
I have the same error message "couldn't allocate a DMA channel" when checking dmesg.

I am using raspberry pi model 2B, Linux raspberrypi 4.1.15-v7+ #830

I will appreciate any help

**Comment by notro** [comment]
You're probably better off trying the raspberry pi forums, more people read the posts.
