### ISSUE TITLE
ili9325 (hy28b) not work

### ISSUE THREAD

**Issue by schuppeste** [notro/fbtft#149]
Screen get darken.. but any test fails.. example mplayer DRI failed.
The Screen gets darkener on module load.
Recompiled Kernel on BananaPi.

No Error in Console or Logs.

DMESG:
[    6.897227] Installing knfsd (copyright (C) 1996 okir@monad.swb.de).
[    7.306163] [spi-inf] Found 2 spi devices in config files
[    7.323340] [spi-inf] boards num modalias         max_spd_hz       bus_num  cs   mode
[    7.339976] [spi-inf] spi_board0 irq gpio not used
[    7.356297] [spi-inf] 0          spidev           12000000         0        0    0x3  
[    7.360159] [spi-inf] spi_board1 irq gpio not used
[    7.375203] [spi-inf] 1          spidev           12000000         0        1    0x3  
[    7.384966] [spi-inf] sun7i_spi_probe: spi0 dma type: normal
[    7.388787] [spi-inf] bus num = 0, spi used = 3 
[    7.401208] [spi-inf] sun7i_spi_probe: spi0 cs bitmap: 0x3
[    7.415511] [spi-inf] sun7i_spi_set_mclk: spi0 source = sdram_pll_p, src_clk = 480000000, mclk 96000000
[    7.421611] sun7i-spi sun7i-spi.0: master is unqueued, this is deprecated
[    7.441519] [spi-inf] sun7i_spi_probe: reuuimlla's SoC SPI Driver loaded for Bus SPI0 with 2 Slaves at most
[    7.467123] [spi-inf] sun7i_spi_probe: spi0 driver probe succeed, base f01e0000, irq 42, dma_id_rx 24, dma_id_tx 24
[    7.592122] fbtft_device:  SPI devices registered:
[    7.623762] fbtft_device:      spidev spi0.0 12000kHz 8 bits mode=0x03
[    7.630011] fbtft_device:      spidev spi0.1 12000kHz 8 bits mode=0x03
[    7.634686] fbtft_device:  'fb' Platform devices registered:
[    7.647618] fbtft_device: Deleting spi0.0
[    7.651530] fbtft_device:  GPIOS used by 'hy28b':
[    7.655888] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[    7.662341] fbtft_device:    'reset' = GPIO25
[    7.665480] fbtft_device:    'led' = GPIO18
[    7.669221] fbtft_device:  SPI devices registered:
[    7.688736] fbtft_device:      spidev spi0.1 12000kHz 8 bits mode=0x03
[    7.700220] fbtft_device:      fb_ili9325 spi0.0 48000kHz 8 bits mode=0x03
[    8.095352] systemd-udevd[111]: starting version 208
[    9.536755] EXT4-fs (sda2): mounted filesystem with ordered data mode. Opts: (null)
[   10.154176] systemd-journald[88]: Received request to flush runtime journal from PID 1
[   10.246763] graphics fb2: fb_ili9325 frame buffer, 240x320, 150 KiB video memory, 4 KiB DMA buffer memory, fps=50, spi0.0 at 48 MHz

**Comment by cvivek2999** [comment]
I am getting display with horizontal colorful lines.I am using hy28b and raspi 3 .I tried noobs and rasbian bt it doesnt works.Also after executing FIRMWARE UPDATE sudo ..URI..rpi-update. Os doesnt start after rebooting.could u tell the connections and steps.i just want to display(no touch features).thnx in advance

**Comment by lwsk** [comment]
Same issue with the horizontal colorful lines using a hy28b and raspberry pi zero with raspbian. @notro, @cvivek2999 any luck?

**Comment by Texy** [comment]
Many displays do not work at the default 48Mhz SPI speed. Try reducing the SPI bus speed to 30Mhz. If that fixes the issue, try increasing the speed until it is still stable.
Texy

**Comment by lwsk** [comment]
@Texy Tried a few speed values in my /boot/config.txt, but still the same problem...

**Comment by lwsk** [comment]
Here's what I get from dmesg:
`pi@raspberrypi:~ $ dmesg | grep fb
[    0.000000] CPU: ARMv6-compatible processor [410fb767] revision 7 (ARMv7), cr=00c5387d
[    0.000000] Kernel command line: bcm2708_fb.fbwidth=656 bcm2708_fb.fbheight=416 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x1ec00000 vc_mem.mem_size=0x20000000  dwc_otg.lpm_enable=0 console=ttyAMA0,115200 console=tty1 root=PARTUUID=2c7bdf7f-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait fbcon=map:10
[   10.649465] fbtft: module is from the staging directory, the quality is unknown, you have been warned.
[   10.676221] fb_ili9325: module is from the staging directory, the quality is unknown, you have been warned.
[   10.677148] fbtft_of_value: buswidth = 8
[   10.677162] fbtft_of_value: debug = 0
[   10.677168] fbtft_of_value: rotate = 90
[   10.677174] fbtft_of_value: fps = 50
[   10.677181] fbtft_of_value: startbyte = 112
[   12.033919] graphics fb1: fb_ili9325 frame buffer, 320x240, 150 KiB video memory, 4 KiB DMA buffer memory, fps=50, spi0.0 at 30 MHz`

**Comment by lwsk** [comment]
It seems like it _should_ be working.

Dmesg tells me that the driver is properly loaded.

During boot, the screen is white then turns black and displays some color lines on a white background, with a line of white moving dots at the bottom of my screen. 

I triple-checked connections, so I'm pretty sure they're good. That said, when I set ledgpio and resetgpio in my devicetree parameters, I do get an error from dmesg, even tho the pins seems good to me. As I said earlier, I also tried a few different speed, but no luck. It seems like that value is only changing the intensity of the color lines.

Framebuffer seems good too. It detects the hardware and set the resolution accordingly.

I hope I didn't bought that screen for nothing... No one had this problem before me?

**Comment by hanswilw** [comment]
@lwsk I am having the same issue, did you end up figuring it out?

**Comment by lwsk** [comment]
Nope...

There seems to be an high percentage of defective units sold, so I just stopped my research there.

[lwsk](https://lwsk.tk/)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by hanswilw** [comment]
@lwsk https://github.com/notro/fbtft/pull/524
