### ISSUE TITLE
LCD has inverted color.

### ISSUE THREAD

**Issue by ParanBada** [notro/fbtft#160]
Hello,
 I installed tinylcd35 on My Raspberry pi. Tinylcd35 is OK, All Color and Text is OK.

And wired another 3.5" LCD.
 This LCD has ILI9486L.
 I used Serial to Perallel Conver Circuit.
 Text and Graphic is displayed.
 But It is Inverted Color. All Color is inverted.
 Black is White, Red is Blue,,,All color is inverted.

/etc/modules as below.
fbtft dma
fbtft_device name=tinylcd35 rotate=270 speed=48000000 fps=50 debug=3 gpio=reset:25,dc:24,led:23
ads7846_device model=7843 gpio_pendown=4 pressure_max=255 x_plate_ohms=100 swap_xy=1 x_min=230 x_max=3850 y_min=190 y_max=3850 verbose=3

Please help me.
What can I do?

Thanks,
SB YIM.

**Comment by tsaG1337** [comment]
Hi,

One quick question. I also have a ILI9486 Display and connected it using the Serial to Parallel circuit. Im using the initialization code as stated on this website here: http://ozzmaker.com/piscreen-driver-install-instructions-2/

One problem is that my color is inverted (black and white as well as colors). Is there any way to fix this? I already tried the bgr option, but this doesnt work for me. 

Thank you!
