### ISSUE TITLE
submitting for mainline linux

### ISSUE THREAD

**Issue by haraldg** [notro/fbtft#161]
Hi,

i think this project is pretty cool. So I wonder why it hasn't been submitted for inclusion in the mainline kernel yet.

Is there a list of things that need to be done before?
Is there any way I can help?

I'd like to use this for a project, but if it was part of the official kernel, that would make things a lot easier.

TIA,
Harald

**Comment by notro** [comment]
FBTFT is now in staging: https://git.kernel.org/cgit/linux/kernel/git/gregkh/staging.git/tree/drivers/staging/fbtft?h=staging-testing

https://github.com/notro/fbtft/wiki/Development
