### ISSUE TITLE
Blank screen with fbtft on Pi with Adafruit13m

### ISSUE THREAD

**Issue by kenrestivo** [notro/fbtft#169]
I'm trying to get one of these going with the Pi.

Running your kernel:

```
Nov  3 00:30:02 raspberrypi kernel: [    0.000000] Linux version 3.12.25+ (pi@raspi2) (gcc version 4.8.3 20140106 (prerelease) (crosstool-NG linaro-1.13.1-4.8-2014.01 - Linaro GCC 2013.11) ) #1 PREEMPT Sat Aug 2 18:11:04 CEST 2014
```

As installed via your instructions here https://github.com/notro/fbtft/wiki#step-by-step-using-fbtft, specifically

```
sudo REPO_URI=https://github.com/notro/rpi-firmware rpi-update
```

(Tried the built-in branch too, no better luck)

Using fbtft_device as documented, the /dev/fb1 device shows up, and data can be written to it, X can even be started on it, but the screen remains blank.

Results here:

```
Nov  3 00:12:06 raspberrypi kernel: [   13.164655] bcm2708_spi bcm2708_spi.0: DMA channel 4 at address 0xf2007400 with irq 20
Nov  3 00:12:06 raspberrypi kernel: [   13.304928] bcm2708_spi bcm2708_spi.0: DMA channel 5 at address 0xf2007500 with irq 21
Nov  3 00:12:06 raspberrypi kernel: [   13.641544] bcm2708_spi bcm2708_spi.0: SPI Controller at 0x20204000 (irq 80)
Nov  3 00:12:06 raspberrypi kernel: [   13.800763] bcm2708_spi bcm2708_spi.0: SPI Controller running in dma mode
Nov  3 00:13:16 raspberrypi kernel: [   87.226237] fbtft_device:  SPI devices registered:
Nov  3 00:13:16 raspberrypi kernel: [   87.226286] fbtft_device:      spidev spi0.0 500kHz 8 bits mode=0x00
Nov  3 00:13:16 raspberrypi kernel: [   87.226303] fbtft_device:      spidev spi0.1 500kHz 8 bits mode=0x00
Nov  3 00:13:16 raspberrypi kernel: [   87.226312] fbtft_device:  'fb' Platform devices registered:
Nov  3 00:13:16 raspberrypi kernel: [   87.226331] fbtft_device:      bcm2708_fb id=-1 pdata? no
Nov  3 00:13:16 raspberrypi kernel: [   87.226387] fbtft_device: Deleting spi0.0
Nov  3 00:13:16 raspberrypi kernel: [   87.226978] fbtft_device:  GPIOS used by 'adafruit13m':
Nov  3 00:13:16 raspberrypi kernel: [   87.227002] fbtft_device:    'reset' = GPIO25
Nov  3 00:13:16 raspberrypi kernel: [   87.227012] fbtft_device:    'dc' = GPIO24
Nov  3 00:13:16 raspberrypi kernel: [   87.227021] fbtft_device:  SPI devices registered:
Nov  3 00:13:16 raspberrypi kernel: [   87.227034] fbtft_device:      spidev spi0.1 500kHz 8 bits mode=0x00
Nov  3 00:13:16 raspberrypi kernel: [   87.227046] fbtft_device:      fb_ssd1306 spi0.0 16000kHz 8 bits mode=0x00
Nov  3 00:13:16 raspberrypi kernel: [   87.424303] graphics fb1: fb_ssd1306 frame buffer, 128x64, 16 KiB video memory, 4 KiB DMA buffer memory, fps=20, spi0.0 at 16 MHz
```

Whilst writing data to the framebuffer, I had a look at the interrupts in /proc, and saw

```
     80:        196   ARMCTRL  bcm2708_spi.0
     20:         58   ARMCTRL  bcm2708_spi.0
```

So something is interrupting, at least.

Everything is connected correctly per your instructions here: https://github.com/notro/fbtft/wiki/LCD-Modules#adafruit-13-monochrome

And while data was supposedly being transferred, I had a look at the data on the lines with a multimeter. 6 of the 7 lines that needed to be connected were high (at various levels) but the CLK line was low!  Shouldn't it be oscillating (at 16Mhz or so)?

I also tried building a very latest kernel 3.12.31+, folding in the fbtft driver as instructed, built and installed well, but got same results as above. I have not tried the Device Tree version yet because it is not clear in the documentation how to set up the device tree for this specific device (the examples cite another device).

Are those instructions out-of-date? Am I doing something obviously wrong?

**Comment by fredoche** [comment]
@kenrestivo It seems that I am hitting the same issue, with a blank screen. How did you finally load the fbtft_device module ? I would really appreciate more info about how you made the screen work.
Thanks

**Comment by kenrestivo** [comment]
@fredoche I simply used a lower frequency. 6Mhz worked, I think I backed it down to 2Mhz because it didn't need to be refreshed that quickly anyway.

**Comment by fredoche** [comment]
Ok I'll try that, thanks

**Comment by fredoche** [comment]
I get a kernel error with speed=2000 (2mhz) 
modprobe fbtft_device name=adafruit13m debug=1  speed=2000
modprobe: ERROR: could not insert 'fbtft_device': Operation not permitted
Could you eventually copy paste the actual modprobe command you loaded the driver with?

**Comment by notro** [comment]
Run the command as root: sudo modprobe ...

**Comment by fredoche** [comment]
I was already logged as root.
I certainly got something wrong about the gpio ports.
I used the following line
modprobe fbtft_device name=adafruit13m debug=1 speed=2000000 gpios=reset:24,dc:23
to go with the following wiring
https://learn.adafruit.com/ssd1306-oled-displays-with-raspberry-pi-and-beaglebone-black/wiring
Now fbi is able to show some stuff on the screen. thx for your help.

**Comment by gatuno1** [comment]
Hello:
I had succesfully tried an ssd1306 from waveshare (http://www.waveshare.com/product/modules/oleds-lcds/oled/0.96inch-oled-b.htm) with 3.2MHz and 3.9MHz (speed=3200000 or speed=3900000) taking account of the wiki page of parameters passing (https://github.com/notro/fbtft/wiki/fbtft_device#parameters%29) and expanding the buffersize:
´´´sh
sudo modprobe fbtft_device name=adafruit13m speed=3900000 txbuflen=32768 fps=30
´´´
I will try with 7.8MHz as stated from RPI documentation (https://www.raspberrypi.org/documentation/hardware/raspberrypi/spi/README.md), as from the datasheet of SSD1306 the max speed would be 10MHz (min tSCLK of 100ns).
