### ISSUE TITLE
Touch Screen - No calibration devices found

### ISSUE THREAD

**Issue by eolandro** [notro/fbtft#242]
Hi,

i have a little problem, the screen is working very but the touch screen does no work and when a run xinput_calibrate a get this

DEBUG: XInputExtension version is 2.2
DEBUG: Skipping virtual master devices and devices without axis valuators.
DEBUG: Skipping device 'Virtual core XTEST pointer' id=4, does not report Absolute events.

maybe a kernel module is missing or a Xorg extension?

dmesg gets me this:

[   12.494577] i2c /dev entries driver
[   12.689566] fbtft_device:  SPI devices registered:
[   12.702896] fbtft_device:      spidev spi0.0 500kHz 8 bits mode=0x00
[   12.709310] fbtft_device:      spidev spi0.1 500kHz 8 bits mode=0x00
[   12.724699] fbtft_device:  'fb' Platform devices registered:
[   12.730437] fbtft_device:      bcm2708_fb id=-1 pdata? no
[   12.736036] fbtft_device:  I2C devices registered:
[   12.740862] fbtft_device:       i2c-0  addr 48896  IRQ 0
[   12.746399] fbtft_device:       i2c-1  addr 48896  IRQ 1
[   12.751741] fbtft_device:      pcm5122 1-004d  addr 77  IRQ 0
[   12.757599] fbtft_device:      wm8804 1-003b  addr 59  IRQ 0
[   12.763415] fbtft_device:      pcm5122 1-004c  addr 76  IRQ 0
[   12.842693] fbtft_device: Deleting spi0.1 (spi0.1)
[   12.853133] stmpe-spi spi0.1: unknown chip id: 0x0
[   12.858010] stmpe-spi: probe of spi0.1 failed with error -22
[   12.879422] fbtft_device: Deleting spi0.0 (spi0.0)
[   12.885034] fbtft_device:  GPIOS used by 'adafruitrt28':
[   12.890389] fbtft_device:    'dc' = GPIO25
[   12.912817] fbtft_device:  SPI devices registered:
[   12.917685] fbtft_device:      stmpe610 spi0.1 500kHz 8 bits mode=0x00
[   12.927899] fbtft_device:      fb_ili9340 spi0.0 32000kHz 8 bits mode=0x00
[   13.070454] Adafruit Industries' power switch driver v1.7
[   13.318952] Console: switching to colour frame buffer device 40x30
[   13.345809] graphics fb1: fb_ili9340 frame buffer, 320x240, 150 KiB video memory, 4 KiB DMA buffer memory, fps=20, spi0.0 at 32 MHz

lsmod:

Module                  Size  Used by
fuse                   78897  3 
evdev                  11975  4 
rpi_power_switch        3979  0 
fb_ili9340              3148  2 
fbtft_device           30462  0 
fbtft                  32828  2 fb_ili9340,fbtft_device
fb_sys_fops             1427  1 fbtft
sysimgblt               2687  1 fbtft
sysfillrect             5194  1 fbtft
syscopyarea             4323  1 fbtft
i2c_dev                 5593  0 
snd_bcm2835            20598  0 
snd_soc_wm8804          8180  0 
snd_soc_pcm512x         8932  0 
snd_soc_bcm2708_i2s     6483  0 
regmap_mmio             2850  1 snd_soc_bcm2708_i2s
snd_soc_core          134535  3 snd_soc_pcm512x,snd_soc_wm8804,snd_soc_bcm2708_i2s
regmap_spi              1956  3 snd_soc_pcm512x,snd_soc_wm8804,snd_soc_core
snd_pcm_dmaengine       5489  1 snd_soc_core
snd_pcm                87655  3 snd_bcm2835,snd_soc_core,snd_pcm_dmaengine
snd_page_alloc          5160  1 snd_pcm
regmap_i2c              1653  3 snd_soc_pcm512x,snd_soc_wm8804,snd_soc_core
snd_compress            8230  1 snd_soc_core
snd_seq                62109  0 
snd_timer              21056  2 snd_pcm,snd_seq
snd_seq_device          6446  1 snd_seq
leds_gpio               2175  0 
led_class               4115  1 leds_gpio
snd                    66386  7 snd_bcm2835,snd_soc_core,snd_timer,snd_pcm,snd_seq,snd_seq_device,snd_compress
spi_bcm2708             5352  0 
rpi_pwm                 6656  0 
i2c_bcm2708             4734  0 

on a system

Linux raspberrypi 3.12.26+ #7 PREEMPT Wed Sep 17 14:25:24 EDT 2014 armv6l GNU/Linux

**Comment by notro** [comment]
> [ 12.853133] stmpe-spi spi0.1: unknown chip id: 0x0

The driver doesn't find the touch controller.
You better ask about this in the Adafruit forums: https://forums.adafruit.com/viewforum.php?f=50

**Comment by eolandro** [comment]
thanks!!!
