### ISSUE TITLE
Support I2C mode for SSD1306

### ISSUE THREAD

**Issue by dword1511** [notro/fbtft#261]
It seems that only SPI mode is supported. However, there are also a lot of I2C modules based on SSD1306.

A example of a dual-mode driver: https://github.com/hallard/ArduiPi_SSD1306.git

**Comment by notro** [comment]
There's already a driver for that: http://lxr.free-electrons.com/source/drivers/video/fbdev/ssd1307fb.c

**Comment by dword1511** [comment]
Thanks for the info.
