### ISSUE TITLE
Datasheet for 2.4 LCD ili9325

### ISSUE THREAD

**Issue by playmonkey** [notro/fbtft#272]
I bought a 2.4 ili9325 lcd (34pin header) from ebay and connected it in parallel (8bit) mode using pins DB10:DB17 and cannot get it to work other than display the background light. I don't have the datasheet and neither does the ebay vendor.

I have another ili9325 2.4 lcd display (different pin markings) that is working fine using custom pin settings with fbtft_device.

Could the 'non-working' lcd be configured for 16bit? The LCD has R1-R8 resistors.  Resistors R4-R2 are empty and 0Ohm (really links) are connected to R1 and R3. 

Any help would be great to get the LCD working. 

Thanks in advance.

**Comment by mrmonteith** [comment]
If you can give the link to the ebay item or a pic we can probably find the datasheet for it.

**Comment by playmonkey** [comment]
Thanks for responding :) Here is an image of the LCD pin header
![wp_20150507_003](https://cloud.githubusercontent.com/assets/4104672/7726614/2e10c8b8-fefb-11e4-9ff6-856f65680288.jpg)

**Comment by NicolasRam** [comment]
Hi! Did you succeed to make it work in 8bit parallel mode ? I'm searching some information for mine. Thanks
