### ISSUE TITLE
error message: write_vmem failed to update display buffer without printed error-code

### ISSUE THREAD

**Issue by msperl** [notro/fbtft#274]
the status returned when calling par->fbtftops.write_vmem inside fbtft_update_display is not printed
only the error message:
```
fbtft_update_display: write_vmem failed to update display buffer
```
please also print the error code - hence add "- %d",ret to the parameters of dev_err().

Maybe also print the function vector via "%pF",par->fbtftops.write_vmem

Something similar to this:
```
diff --git a/drivers/staging/fbtft/fbtft-core.c b/drivers/staging/fbtft/fbtft-co
index 53b748b..6e7fa1a 100644
--- a/drivers/staging/fbtft/fbtft-core.c
+++ b/drivers/staging/fbtft/fbtft-core.c
@@ -405,8 +405,8 @@ static void fbtft_update_display(struct fbtft_par *par, unsi
        ret = par->fbtftops.write_vmem(par, offset, len);
        if (ret < 0)
                dev_err(par->info->device,
-                       "%s: write_vmem failed to update display buffer\n",
-                       __func__);
+                       "%s: write_vmem failed to update display buffer - %pF returned %d\n",
+                       __func__, par->fbtftops.write_vmem, ret);

        if (unlikely(timeit)) {
                getnstimeofday(&ts_end);
```

There may be others that also fail without reporting the return code...

**Comment by notro** [comment]
Development is done in the staging tree: https://github.com/notro/fbtft/wiki/Development
fbtft is on hold for me now. I sent a patchset proposal on how to move it forward, but Greg didn't reply, so I kind of gave up and moved on to other things. I'll wait and see if someone comes along that has interest in fbtft as a whole.
