### ISSUE TITLE
display: hy-1.8 spi

### ISSUE THREAD

**Issue by ste1s** [notro/fbtft#28]
Not working on st7735
I did everything according to the instructions where I could make a mistake?

HY-1.8 J1        Raspberry Pi P1
1 - GND          - P1.6 GND
2 - VCC          - P1.2 5V Power
3 - NC
4 - NC
5 - NC
6 - RESET        - P1.22 GPIO25
7 - A0           - P1.18 GPIO24
8 - SDA          - P1.19 GPIO10 MOSI
9 - SCK          - P1.23 GPIO11 SCLK
10 - CS          - P1.24 GPIO8 CE0
11 - SD_SCK
12 - SD_MISO
13 - SD_MOSI
14 - SD_CS
15 - LED+         - P1.4 5V Power
16 - LED-         - P1.9 GND

dmesg log:
http://pastebin.com/Kkq6fQGh

**Comment by anyurj** [comment]
@Ardakilic If i follow your instructions, will the tft be the only output? Or I still can use my TV as output via HDMI cable? Thanks.
