### ISSUE TITLE
Raspberry Pi 2 with Ubuntu Mate and Waveshare 32b

### ISSUE THREAD

**Issue by bkems** [notro/fbtft#298]
Hi notro

I'm confused about the status of the fbtft drivers and the debian kernel. Can I install the fbtft drivers on Ubuntu Mate? Or don't I need to? lsmod doesn't show fbtft listed. I bricked a Pi 2 running Raspian Jessie by installing the fbtft drivers and I'd like not to do that again if possible.

If someone reads this who has done this before or knows what I need to do I'd love to get some help. :-)

Guy

**Comment by jonklinger** [comment]
this is a comment to see when the solution comes.

**Comment by notro** [comment]
This looks to be solved now, from changelog:

2015-10-14 - Ubuntu MATE 15.10 for Raspbery Pi 2 Release Candidate
* Updated to Linux 4.1.10.
Now using the kernel, firmware and drivers from Raspberry Pi Foundation and includes rpi-update to easily update the kernel and firmware.


https://ubuntu-mate.org/raspberry-pi/

**Comment by notro** [comment]
Closing old issues, reopen if needed.
