### ISSUE TITLE
Add 16bit mode for itdb28 driver

### ISSUE THREAD

**Issue by Kukunin** [notro/fbtft#310]
I have this lcd screen [ITDB02-2.4e](http://imall.itead.cc/display/tft-lcm/itdb02-2-4e.html), which perfectly works with itdb28 fbtft_device driver in 8bit. 

That lcd has 8bit/16bit modes switcher, and since Raspberry PI 2 has enough GPIO pins, it would be cool to have support of 16bit. I think, it should double (or at least increase 1.5x times) fps of the screen.

**Comment by notro** [comment]
Closing old issues, reopen if needed.
