### ISSUE TITLE
DTS file for Adafruit 13m on Raspberry Pi 2 is available here

### ISSUE THREAD

**Issue by kenrestivo** [notro/fbtft#321]
https://github.com/kenrestivo/linux/blob/3d61a22b05cbf7ac2f6b620dcd45c2fb49fb9442/arch/arm/boot/dts/overlays/adafruit13m-overlay.dts

**Comment by notro** [comment]
Thanks, I put it here: https://github.com/notro/fbtft/wiki/FBTFT-RPI-overlays#overlays
