### ISSUE TITLE
Possible to have two LCDs displaying same content?

### ISSUE THREAD

**Issue by digitalman2112** [notro/fbtft#322]
Is it possible to have two LCDs displaying the same content? I have an application that requires a small lcd on either side of a partition showing the same video, and didnt know if this was possible either by simply branching the SPI signals or through driver configuration.

**Comment by notro** [comment]
I don't see any problem in connecting 2 similar displays to the same SPI Chip Select line (don't connect MISO). Except for fb_ili9320, no driver tries to read from the controller, and even that doesn't affect functionality.

**Comment by notro** [comment]
Closing old issues, reopen if needed.
