### ISSUE TITLE
1.8" Sainsmart RPi 2, fbtft_request_gpios fail -16 

### ISSUE THREAD

**Issue by andolfss** [notro/fbtft#325]
Hi there, being new to all this, im not sure what is wrong, but I think all is installed properly, but when i run dmesgi get the following: 

fb_st7735r spi0.0: fbtft_request_gpios: gpio_request_one('dc'=24) failed with -16
fb_st7735r: probe of spi0.0 failed with error -16

I got a Sainsmart 1.8" TFT and a a Raspberry Pi 2. 

I'm not sure what I'll do, but ill try anything you'll suggest.

**Comment by notro** [comment]
-16 is EBUSY, so that means someone has already claimed/requested the gpio.

**Comment by andolfss** [comment]
So how do i Find who uses it? or should i just change to different GPIO?

**Comment by notro** [comment]
The troubleshooting section shows how to do that: http://aron.ws/projects/lirc_rpi/

**Comment by notro** [comment]
Closing old issues, reopen if needed.
