### ISSUE TITLE
how to support ili9163

### ISSUE THREAD

**Issue by semico** [notro/fbtft#330]
I've notice that https://github.com/torvalds/linux/tree/master/drivers/staging/fbtft has got the ili9163 supported. But how can i use it on raspbian? What shall I do? I don't know about linux programming, just wanna using the tft screen. could you pls give me some hint or tutorial?

**Comment by notro** [comment]
Ask here about getting FB_TFT_ILI9163 enabled: https://github.com/raspberrypi/linux/issues
```
$ sudo modprobe configs
$ zgrep 9163 /proc/config.gz
# CONFIG_FB_TFT_ILI9163 is not set
```

**Comment by notro** [comment]
Closing old issues, reopen if needed.
