### ISSUE TITLE
fbtft incompatable with Adafruit 2.8" ILI9341 breakout board?

### ISSUE THREAD

**Issue by ArduinoKid** [notro/fbtft#331]
Currently I am trying to use an Adafruit 2.8" ILI9341 breakout board ( http://bit.ly/1xPvFbw ) with fbtft however I can't seem to get it working. I am not sure if the display is truely imcompatable or if i am simply doing something wrong. If someone could tell me if they have got this display working or If anyone could post instructions to get this display working in spi mode or can post a link to the instructions it would be greatly appreciated.
Thanks in advance.

**Comment by notro** [comment]
Closing old issues, reopen if needed.
