### ISSUE TITLE
duplicate of issue 303

### ISSUE THREAD

**Issue by tyler-kalevra** [notro/fbtft#334]
I'm running pidora on a rev 1 pi.
trying to run the autorun is failing.

Any input or missing information is appreciated.

[root@raspi xf86-video-fbturbo-master]# ./autogen.sh
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal
configure.ac:38: error: must install xorg-macros 1.8 or later before running autoconf/autogen
configure.ac:38: the top level
autom4te: /usr/bin/m4 failed with exit status: 1
aclocal: error: /usr/bin/autom4te failed with exit status: 1
autoreconf: aclocal failed with exit status: 1

**Comment by notro** [comment]
No point in duplicating the post. If someone could help you with this off topic issue you would have heard it by now. Closing.
