### ISSUE TITLE
SSD 1289 to raspberry pi 2

### ISSUE THREAD

**Issue by Zerglrisk** [notro/fbtft#348]
Hi mr. notro, i have an question. i trying to install my raspberry py 2. and it cant work do that. 
im using Linux 3.18.16-v7.
how can i install it?

**Comment by notro** [comment]
If you need help updating the kernel I suggest you go to the Pi forums for help: https://www.raspberrypi.org/forums/

**Comment by notro** [comment]
Closing old issues, reopen if needed.
