### ISSUE TITLE
Cannot display in 2.4 LCD use itdb28 (ili9325)

### ISSUE THREAD

**Issue by nguyenhunga5** [notro/fbtft#354]
My LCD not display, my lcd is v1.3. I already try with:
sudo modprobe fbtft_device name=itdb28 rotate=90 fps=60 gpios=dc:3,reset:15,wr:2,cs:7,db0:17,db1:18,db2:27,db3:22,db4:23,db5:24,db6:25,db7:4
sudo modprobe fb_ili9325 width=240 height=320 buswidth=8 init=-1,0x0013,0xCC00,-1,0x0011,0x2004,-1,0x0015,0x2600,-1,0x0014,0x252A,-1,0x0012,0x0033,-1,0x0013,0xCC04,-2,5,-1,0x0013,0xCC06,-2,5,-1,0x0013,0xCC4F,-2,5,-1,0x0013,0x674F,-1,0x0011,0x2003,-2,5,-1,0x0030,0x2609,-1,0x0031,0x242C,-1,0x0032,0x1F23,-1,0x0033,0x2425,-1,0x0034,0x2226,-1,0x0035,0x2523,-1,0x0036,0x1C1A,-1,0x0037,0x131D,-1,0x0038,0x0B11,-1,0x0039,0x1210,-1,0x003A,0x1315,-1,0x003B,0x3619,-1,0x003C,0x0D00,-1,0x003D,0x000D,-1,0x0016,0x0007,-1,0x0002,0x0013,-1,0x0003,0x0009,-1,0x0001,0x0127,-2,5,-1,0x0008,0x0303,-1,0x000A,0x000B,-1,0x000B,0x0003,-1,0x000C,0x0000,-1,0x0041,0x0000,-1,0x0050,0x0000,-1,0x0060,0x0005,-1,0x0070,0x000B,-1,0x0071,0x0000,-1,0x0078,0x0000,-1,0x007A,0x0000,-1,0x0079,0x0007,-1,0x0007,0x0051,-2,5,-1,0x0007,0x0053,-1,0x0079,0x0000,-3

Or
sudo modprobe fbtft_device name=flexpfb gpios=dc:3,reset:15,wr:2,cs:7,db0:17,db1:18,db2:27,db3:22,db4:23,db5:24,db6:25,db7:4 debug=3

sudo modprobe flexfb width=240 height=320 buswidth=8 init=-1,0x0013,0xCC00,-1,0x0011,0x2004,-1,0x0015,0x2600,-1,0x0014,0x252A,-1,0x0012,0x0033,-1,0x0013,0xCC04,-2,5,-1,0x0013,0xCC06,-2,5,-1,0x0013,0xCC4F,-2,5,-1,0x0013,0x674F,-1,0x0011,0x2003,-2,5,-1,0x0030,0x2609,-1,0x0031,0x242C,-1,0x0032,0x1F23,-1,0x0033,0x2425,-1,0x0034,0x2226,-1,0x0035,0x2523,-1,0x0036,0x1C1A,-1,0x0037,0x131D,-1,0x0038,0x0B11,-1,0x0039,0x1210,-1,0x003A,0x1315,-1,0x003B,0x3619,-1,0x003C,0x0D00,-1,0x003D,0x000D,-1,0x0016,0x0007,-1,0x0002,0x0013,-1,0x0003,0x0009,-1,0x0001,0x0127,-2,5,-1,0x0008,0x0303,-1,0x000A,0x000B,-1,0x000B,0x0003,-1,0x000C,0x0000,-1,0x0041,0x0000,-1,0x0050,0x0000,-1,0x0060,0x0005,-1,0x0070,0x000B,-1,0x0071,0x0000,-1,0x0078,0x0000,-1,0x007A,0x0000,-1,0x0079,0x0007,-1,0x0007,0x0051,-2,5,-1,0x0007,0x0053,-1,0x0079,0x0000,-3

This is my screen:
http://imgur.com/a/LoTIK

Please help me. Thanks

**Comment by notro** [comment]
Closing old issues, reopen if needed.
