### ISSUE TITLE
FT6x06 and pitft lcd driver 

### ISSUE THREAD

**Issue by Pawnies** [notro/fbtft#356]
Hello  i'm using pitft on my olimex A10 board based on allwinner A10 chip.
Lcd works fine with notro drivers but i can't use capacitive touch.
I have compiled kernel with adafruit driver using this posts:
http://immerhax.com/ and https://learn.adafruit.com/adafruit-2-8-pitft-capacitive-touch

Compilation works fine but cause i'm using a kernel with script.bin instead of dtb file, i can't use the driver.

Question: can i replace dtb parameters with sudo modprobe with arguments?
Or must i adapted driver to be used with script.bin?

This driver of same family ft5X worked fine with my board and script.bin parameters:
https://github.com/linux-sunxi/linux-sunxi/blob/sunxi-3.4/drivers/input/touchscreen/ft5x_ts.c
http://linux-sunxi.org/Fex_Guide#.5Bctp_para.5D

Thank you very much !!!

**Comment by notro** [comment]
That driver is in mainline now [drivers/input/touchscreen/ft6236.c](https://github.com/torvalds/linux/blob/master/drivers/input/touchscreen/ft6236.c)

> Question: can i replace dtb parameters with sudo modprobe with arguments?

Sure, you can even hardcode the values if you're the only one using the kernel binary.

**Comment by notro** [comment]
Closing old issues, reopen if needed.
