### ISSUE TITLE
ILI9341 Driver on BBB with Debian 8.2(Jessie)

### ISSUE THREAD

**Issue by umesh4b4** [notro/fbtft#358]
Hi Notro,

I am trying to create frame buffer for ili9341 lcd using Device tree overlay file. SPI is getting registered but i did not see any /dev/fbx. Do I need to change any thing in device tree file for latest kernel.

Same driver files and device tree file are working on debian 7.x versions.

Below is my log file data:

[  108.162679] bone_capemgr bone_capemgr: part_number 'LCD-ILI9341', version 'N/A'
[  108.170197] bone_capemgr bone_capemgr: slot #4: override
[  108.185671] bone_capemgr bone_capemgr: Using override eeprom data at slot 4
[  108.193365] bone_capemgr bone_capemgr: slot #4: 'Override Board Name,00A0,Override Manuf,LCD-ILI9341'
[  108.238498] ocp:backlight supply power not found, using dummy regulator
[  108.262852] bone_capemgr bone_capemgr: slot #4: dtbo 'LCD-ILI9341-00A0.dtbo' loaded; overlay id #0
[  108.347123] ocp:backlight supply power not found, using dummy regulator
[  108.360461] omap2_mcspi 481a0000.spi: registered master spi1
[  108.385314] spi spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.385401] spi spi1.0: setup mode 3, 8 bits/w, 64000000 Hz max --> 0
[  108.386022] omap2_mcspi 481a0000.spi: registered child spi1.0
[  108.438318] fbtft: module is from the staging directory, the quality is unknown, you have been warned.
[  108.481997] fb_ili9341: module is from the staging directory, the quality is unknown, you have been warned.
[  108.523205] fbtft_of_value: regwidth = 8
[  108.527193] fbtft_of_value: buswidth = 9
[  108.533145] fbtft_of_value: rotate = 90
[  108.568584] fbtft_of_value: fps = 50
[  108.718431] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.718472] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.726235] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.726273] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.726361] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.726380] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.726422] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.726440] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.726478] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.726495] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.726533] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.726551] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.726588] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.726605] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.726643] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.726659] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.726697] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.726713] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.726749] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.726766] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.726803] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.726820] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.726857] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.726874] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.726912] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.726928] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.726965] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.726982] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.727019] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.727035] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.727071] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.727088] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.727124] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.727142] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.727179] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.727195] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.851476] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.851514] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.874451] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.874489] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.874557] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.874576] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.874615] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.874633] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.874671] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.874687] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted
[  108.875225] fb_ili9341 spi1.0: setup: speed 48000000, sample trailing edge, clk inverted

Thanks

**Comment by notro** [comment]
> Do I need to change any thing in device tree file for latest kernel.

Not that I know of.

**Comment by notro** [comment]
Closing old issues, reopen if needed.
