### ISSUE TITLE
Sorry, I think I need your help

### ISSUE THREAD

**Issue by sx515** [notro/fbtft#359]
CC [M]  drivers/video/fbtft/fbtft-core.o
drivers/video/fbtft/fbtft-core.c: In function ‘fbtft_request_gpios’:
drivers/video/fbtft/fbtft-core.c:144:5: error: implicit declaration of function ‘devm_gpio_request_one’ [-Werror=implicit-function-declaration]
cc1: some warnings being treated as error

Now, I do not know how to do :-(
My Kernel : 3.4
I hope you can help me find an optimal solution.
Thank you.

**Comment by notro** [comment]
devm_gpio_request_one() came with 3.5

**Comment by notro** [comment]
Closing old issues, reopen if needed.
