### ISSUE TITLE
FBTFT Module Failing to load at startup

### ISSUE THREAD

**Issue by theLuthier** [notro/fbtft#369]
I’m using a 2.2″ SPI TFT display with my RPi2. In conjunction with RetroPie 3.2, everything worked fine with FBTFT and FBCP working at startup. I’ve since installed Retropie 3.4 and I keep running into 2 problems:

1 -- FBTFT module fails to load when added to /etc/modules.

![screen-shot-2016-02-01-at-3 29 16-pm](https://cloud.githubusercontent.com/assets/3266998/12806341/27c2c0c0-cad3-11e5-8e57-3a5c75042608.png)

I’ve managed to work around it by adding “modprobe fbtft_device name=adafruit22a” to /etc/rc.local, however it only works about 50% of the time. The module loading after reboot seems to be determined by the flip of a coin..

2 -- Following the trend, FBCP only runs at startup about 50% of the time. I've tried adding “/usr/local/bin/fbcp &” seemingly everywhere I've seen suggested online: rc.local, init.d/asplashscreen, my own custom startup script as recommend in the wiki (http://www.stuffaboutcode.com/2012/06/raspberry-pi-run-program-at-start-up.html).

However as soon as I get to the console, “modprobe fbtft_device” loads fine as does “fbcp&”. So this tells me that perhaps there’s an issue with when the module loads and when/if the fbcp command runs.

Any help is _very_ appreciated at this point.

PS - Huge thanks to notro for making this possible in the first place!

**Comment by notro** [comment]
Have you followed this: https://github.com/notro/fbtft/wiki#make-it-permanent-debian-jessie-arch-linux-systemd

**Comment by theLuthier** [comment]
Thanks for the repy, notro. Yes I have, here's the output from dmesg:

![screen shot 2016-02-04 at 3 21 37 pm](https://cloud.githubusercontent.com/assets/3266998/12828486/26630c28-cb53-11e5-8b99-38099447b4ed.png)

**Comment by notro** [comment]
This kernel seem to be using the out-of-tree [spi-bcm2708](https://github.com/notro/spi-bcm2708/blob/master/spi-bcm2708.c) driver, so you need to specify spi-bcm2708 instead of spi-bcm2835.

**Comment by theLuthier** [comment]
That *seems* to have fixed it! Though dmesg still gives an error:

![screen shot 2016-02-04 at 4 19 35 pm](https://cloud.githubusercontent.com/assets/3266998/12830027/285b6658-cb5b-11e5-9b54-5cac0e7a1d06.png)

I'm used to this working sometimes and not others, so I'll give it a couple days and update if this appears to be a permanent fix. Thanks a ton for the help!

**Comment by notro** [comment]
If you add ```debug``` to /boot/cmdline.txt, you'll get a lot of systemd debug messages in the kernel log. Maybe that can aid you in tracking down the reason for the error.

**Comment by theLuthier** [comment]
Oh nice, thanks for the suggestion - I'll certainly try it.

**Comment by notro** [comment]
Closing old issues, reopen if needed.

**Comment by Zhairgling** [comment]
Hi did you solved this error ? I've the same : 

![image](https://cloud.githubusercontent.com/assets/16452670/23746095/fec67978-04ba-11e7-9c08-4bc51e46ad51.png)
