### ISSUE TITLE
Sainsmart 18 tft not working on RPi 3

### ISSUE THREAD

**Issue by 11ishan** [notro/fbtft#407]
Hey notro,
I'm facing a similar problem as this guy. 
http://raspberrypi.stackexchange.com/questions/37611/tft-kernel-module-not-loading-on-startup

Please could you help me out with it?
Thank you

**Comment by 11ishan** [comment]
The screen becomes black after i load the drivers using modprobe, but doesn't display anything

**Comment by notro** [comment]
This might help: https://github.com/notro/fbtft/wiki#make-it-permanent-debian-jessie-arch-linux-systemd

**Comment by 11ishan** [comment]
I tried the steps you suggested,  but no luck.
Dmesg is showing me an error " Failed to start load kernel modules.

**Comment by 11ishan** [comment]
The driver is loading properly, but the display isn't displaying anything, just a black screen as soon as i use modprobe

**Comment by 11ishan** [comment]
And there is no fbtft.conf file in both locations

**Comment by notro** [comment]
> The driver is loading properly, but the display isn't displaying anything, just a black screen as soon as i use modprobe

That's expected. This will put console 1 on /dev/fb1:
con2fbmap 1 1

For X windows see: https://github.com/notro/fbtft/wiki/FBTFT-on-Raspian

**Comment by 11ishan** [comment]
If i edit the 99-fbturbo.conf file, i get an error saying failed to load kernel modules and later i get failed to start light display manager.  During boot.

**Comment by 11ishan** [comment]
It seems fbtft drivers aren't compatible with RPi 3.   The drivers start loading bcm2708_fb* various stuff like width, height etc.

**Comment by 11ishan** [comment]
Using journalctl -xn,  i get the following error 

Host name not found:  0.debian.pool
Host name not found:  1.debian.pool
Host name not found:  2.debian.pool
Host name not found:  3.debian.pool

**Comment by 11ishan** [comment]
And, 
Host name not found:  0.debian.pool.ntp.org
Host name not found: 1.debian.pool.ntp.org
Host name not found:  2.debian.pool.ntp.org
Host name not found:  3.debian.pool.ntp.org

**Comment by notro** [comment]
I think you're better off asking in the Pi forums: https://www.raspberrypi.org/forums/viewforum.php?f=44

**Comment by 11ishan** [comment]
Ok. Thanks for helping me out.

**Comment by 11ishan** [comment]
Got the tft working!!!  Thanks a lot for your help!!!

**Comment by 11ishan** [comment]
As it turns out the fbturbo config file was causing problems.
