### ISSUE TITLE
fb_pcd8544 spi0.0: __spi_sync timeout

### ISSUE THREAD

**Issue by dunglx** [notro/fbtft#435]
Hi,

I have just had a NanoPi 2 Fire board (http://wiki.friendlyarm.com/wiki/index.php/NanoPi_2_Fire). I'm trying to use fbtft driver for the Nokia 3310/5110 display on this board with kernel 3.4. I had enabled fbtft driver with nokia3310 device as the follow command:

    #  modprobe fbtft_device name=nokia3310 debug=7 verbose=3 gpios=dc:71,reset:72,led:92

and get the error:

   [   38.148000] fbtft_device: module is from the staging directory, the quality is unknown, you have been warned.
[   38.172000] fbtft_device:  SPI devices registered:
[   38.184000] fbtft_device:      spidev spi0.0 3125kHz 8 bits mode=0x03
[   38.200000] fbtft_device:  'fb' Platform devices registered:
[   38.208000] fbtft_device:      nxp-fb id=0 pdata? yes
[   38.216000] fbtft_device: Deleting spi0.0
[   38.224000] SSP Target Frequency is: 400000, Effective Frequency is 396825
[   39.352000] fb_pcd8544 spi0.0: __spi_sync timeout
[   39.356000] ssp-pl022 ssp-pl022.0: do_polling_transfer: timeout!
[   39.368000] fb_pcd8544 spi0.0: fbtft_write_reg8_bus8: write() failed and returned -16
[   40.376000] fb_pcd8544 spi0.0: __spi_sync timeout
[   40.380000] fb_pcd8544 spi0.0: fbtft_write_reg8_bus8: write() failed and returned -16
[   41.392000] fb_pcd8544 spi0.0: __spi_sync timeout
[   41.396000] fb_pcd8544 spi0.0: fbtft_write_reg8_bus8: write() failed and returned -16
[   42.408000] fb_pcd8544 spi0.0: __spi_sync timeout
[   42.412000] fb_pcd8544 spi0.0: fbtft_write_reg8_bus8: write() failed and returned -16
[   43.424000] fb_pcd8544 spi0.0: __spi_sync timeout
[   43.428000] fb_pcd8544 spi0.0: fbtft_write_reg8_bus8: write() failed and returned -16
[   44.208000] ssp-pl022 ssp-pl022.0: do_polling_transfer: timeout!
........

May you help me how to resolve this error ?

Thanks,

**Comment by yuewb** [comment]
Hi,dunglx,I also have this same problem,have U solve this ?Thank u very much!
