### ISSUE TITLE
4" touchscreen WaveShare can't switch off the backlight

### ISSUE THREAD

**Issue by Fin3** [notro/fbtft#444]
Hello notro,

i'm in the same trouble of https://github.com/notro/fbtft/issues/320
there seems that there is no way to switch off the backlight of the waveshare 4" rpi touchscreen.

I need that for my domotic use, i really don't want to have the lcd with the backlight always powered.

Can you help us in this? I can give you photo, sample, sketch... please just tell me what you need!

Thank you in advance for your efforts.

p.s. anyway, great work!!!!

**Comment by notro** [comment]
For some reason they don't provide backlight control. Look at the pin table, no led pin: http://www.waveshare.com/4inch-rpi-lcd-a.htm
