### ISSUE TITLE
Can't get above 4FPS with a PiTFT 320x240 connected to a ODROID Xu4

### ISSUE THREAD

**Issue by smlehbleh** [notro/fbtft#461]
I've got a PiTFT 320x240 TFT working on my ODROID Xu4, but its incredibly slow: 4fps transferring at ~700kb/sec according to the debug output.

This is tested from both my own simple C program writing to mmap'ed fb1 and also outputting mplayer to fb1.
I've tried lots of different speed and fps parameters with modprobe fbtft_device, but sadly it won't budge from 4fps.

I saw in another issue that SPI without DMA might reduce fps to very low, but I'm not sure how to tell if this is the issue, or whether or not fbtft is actually using DMA.

**Comment by notro** [comment]
I believe this is better asked in the Odroid forums.
The spi core handles dma, it asks the spi controller driver if it can do dma on the transfer and if so maps it up.
