### ISSUE TITLE
TinyLcd 3.5" remains white

### ISSUE THREAD

**Issue by AndreiAdrian** [notro/fbtft#463]
I use a raspberry pi 3b with jessie.I have rpi updated and  followed the steps to install the display.
The drivers are loaded, lsmod shows 'fb_tinylcd' and 'fbtft', spi is enabled 
'con2fbmap 1 1' doesn't show errors, but still the display is white. Am I missing something?

**Comment by notro** [comment]
You could try lowering the speed. A white display means it's not been configured (correctly).
