### ISSUE TITLE
Adafruit 1.44" fbtft_device custom command ?

### ISSUE THREAD

**Issue by JohnEdwa** [notro/fbtft#464]
This display: https://www.adafruit.com/product/2088

I've gotten a 1.8" red tab working simply with "sudo modprobe fbtft_device name=adafruit18", and a custom at 128x128 with "sudo modprobe fbtft_device custom name=fb_st7735r gpios=reset:25,dc:24,led:18 speed=40000000 fps=15 width=128 height=128".

But how would I init the 1.44", which AFAIK, is identical to the adafruit18_**green** except for the resolution? How do I send the '.fbtftops.set_addr_win = \adafruit18_green_tab_set_addr_win,' part ?

**Comment by notro** [comment]
You have to change fbtft_device (or the driver) and recompile it.
