### ISSUE TITLE
Modify resolution of 1.8 inch compatible with ST7735R to work with 1.44 inch

### ISSUE THREAD

**Issue by acondurache** [notro/fbtft#472]
How to change resolution for the fbtft_device to work with 128x128 displays, currently works for 128x160 only, would I need to rebuild the kernel from scratch or just modify configuration ?

**Comment by LouisPi** [comment]
Did you ever get this working?

**Comment by troyane** [comment]
@acondurache @LouisPi Look at https://github.com/notro/fbtft/wiki/fbtft_device#custom-display -- there is `width` and `height` arguments.

**Comment by LouisPi** [comment]
Thanks!
