### ISSUE TITLE
RA8875 rotate.

### ISSUE THREAD

**Issue by Ferite** [notro/fbtft#476]
Hi Notro.

I have been testing an ER_TFTM043_2 display, with RA8875 controller, interfacing with SPI. So far it works well, but there seems to be a problem with  fbtft_device's rotate param. Value 180 do nothing, and 90 and 270 just shows a black display. This is my code in /etc/modprobe.d/

```
options fbtft dma=0
options fbtft_device name=er_tftm050_2 speed=32000000 busnum=2 fps=40 rotate=90
```

Could you give me some sugestions on if rotate is implemented in this controller, or how can I debug the problem?.

Thanks.

**Comment by notro** [comment]
The driver doesn't support rotate: http://elixir.free-electrons.com/linux/latest/source/drivers/staging/fbtft/fb_ra8875.c

fbtft flips widht/height on rotate=90 and 270 and fb_ra8875 writes to the kernel log: "display size is not supported!!"
