### ISSUE TITLE
tinylcd35 rotate to 270 produce mirrored picture 

### ISSUE THREAD

**Issue by VladoPortos** [notro/fbtft#483]
Hello,
I have my raspberry hooked to tinylcd display ( the cheap 20$ without touch screen ) and if I'm using the old image they provide it works fine, the rotation is fine and so on... how ever I updated to raspbian stretch and here my problem starts. 

I managed to get the display working ok using fbtft and tinylcd35 overlay in boot/config.txt

dtoverlay=tinylcd35,rotate=90,speed=48000000

How ever 
rotate:0 produce image to be vertical 
**rotate: 90 - Makes the image appear correctly but flipped like mirror**
rotate: 180 - produce image to be verticaljust from oposite side as rotate 0
rotate 270 - Image appear ok just flipped horizontaly

so all rotate works fine except the one I needed the most the 270 rotate 

Its this display [http://www.neosecsolutions.com//products.php?95&cPath=28](http://www.neosecsolutions.com//products.php?95&cPath=28)

Any idea how to fix this :(

**Comment by notro** [comment]
This is where the rotation happens: https://github.com/torvalds/linux/blob/master/drivers/staging/fbtft/fb_tinylcd.c#L73

Since they need to provide their own image, they have probably changed the driver without pushing the changes upstream.
