### ISSUE TITLE
FBTFT drivers -- Use in other ARM boards? Nvidia Jetson TX2 board??

### ISSUE THREAD

**Issue by Balajinp** [notro/fbtft#498]
Hi,
Need to use these drivers in Nvidia Jetson Tx2 board? Any changes are required for this?

Please provide the information for this.

-Thanks.

**Comment by notro** [comment]
Not that I'm aware of. fbtft has been in [drivers/staging/fbtft](http://elixir.free-electrons.com/linux/latest/source/drivers/staging/fbtft) since 4.0.
