### ISSUE TITLE
FBTFT driver needs the DMA controller??? Donot want/Donot have to use the DMA

### ISSUE THREAD

**Issue by Balajinp** [notro/fbtft#503]
Hi,
Trying to bring up the SSD1306 controller on other ARM board, not RPI board. For these drivers, whether DMA must??, since I don't want to use the DMA controller. Then how to configure this driver to not use the DMA controller. 

Please help.

-Thanks.

**Comment by Balajinp** [comment]
Checked this, fbtft-core.c, change dma=false, then it will not do the dma.

**Comment by notro** [comment]
The linux spi subsystem uses dma if the hw supports it, otherwise it doesn't. The dma parameter is gone in the latest linux releases.
