### ISSUE TITLE
FBTFT driver -- OLED display (Monochrome) -- Write a single pixel or some pixels 

### ISSUE THREAD

**Issue by Balajinp** [notro/fbtft#504]
Trying to bring up the SSD1306 OLED display (Monochrome). Need to confirm that my device tree values are proper and the device spi access proper before display anything... 

Do you have the function to write the single pixel in OLED display? This function may be in kernel driver or user space applications? This may be in without conversion of RGB or something else. 

-Thanks.

**Comment by Balajinp** [comment]
In write_vmem() in fb_ssd1306.c file, changed this

set the txbuf.buf to 0xFF instead of the user space values, this is for testing

ret = par->fbtftops.write(par, par->txbuf.buf,
                                  par->info->var.xres * par->info->var.yres /
                                  8);
then display prints full pixels on.

**Comment by arunkvnss** [comment]
Do you have any answer for this ?
