### ISSUE TITLE
Setting DMA off from command line, fails

### ISSUE THREAD

**Issue by eorojas** [notro/fbtft#508]
This may be a generic issue or an issue with Ubuntu 4.4.x and not this particular driver.
Any suggestions greatly appreciated.  Here is what I found.
First, I do not have **modprobe** available.  I also do not have DMA.  I am building Linux with a command line that includes "_fbtft_device.dma=0_".  This fails to have any effect on the variable "_static bool dma;_" in **fbtft-core.c**.  I verified that if I changed the code and set dma=false I follow the correct path and I am able to launch the driver.
I also noticed that there is a "_static unsigned int debug;_" in both **fbtft_device.c** and in **fbtft-core.c**.  This seems broken regardless of the problem with "_dma_".  On a hunch, I removed debug and moved _dma_ to the "**device**" code.  I wrote functions _get_dma() and get_debug()_ and replaced references to dma and debug in the "**core**" code so that the code would work as before.  After which I was able to set the _dma_ value from the command line.
I looked around for evidence that either of these was an error but did not find any.  It seems unlikely that two instances of "_debug_" would work.  
Thoughts?
I'm happy to make changes and submit for review.

For reference:
cat /proc/cmdline 
systemd.show_status=auto earlyprintk=ttyS0,115200n1 console=ttyS0,115200n1 reboot=efi fbtft_device.custom=1 fbtft_device.dma=0 fbtft_device.verbose=3 fbtft_device.name=fb_ili9341 fbtft_device.gpios=reset:26,cs:20,dc:12,wr:1,rd:15,db00:9,db01:25,db02:11,db03:8,db04:7,db05:5,db06:6,db07:16 fbtft_device.buswidth=8 fbtft_device.debug=7   reset_devices sugarcube.bootid=24a3985fe9b5b5a2748ecda64c6a6754c9d73134 sugarcube.factoryver=1.1-3-g6b1324f-20180206-1949-prod

**Comment by notro** [comment]
The dma module parameter is gone now, it was just old cruft: [staging: fbtft: remove custom DMA mapped buffer](https://github.com/torvalds/linux/commit/7c3eaadd0209fe21f331600ea2d904c3a0e9b287#diff-314cd2dde02b95642443fc1a08fabf4f)

Wrt to the fbtft.ko debug module argument, it can probably just be removed.
