### ISSUE TITLE
touch for waveshare22

### ISSUE THREAD

**Issue by hanzala123** [notro/fbtft#509]
i have a a waveshare22 display which uses XPT2046 touch driver .but the driver in fbtft is for  ads7846. so how do i install the driver for XPT2046?????

**Comment by notro** [comment]
XPT2046 is supported by ads7846: [Documentation/devicetree/bindings/input/ads7846.txt](https://www.kernel.org/doc/Documentation/devicetree/bindings/input/ads7846.txt)
