### ISSUE TITLE
Initializing fbtft and associated drivers very early on

### ISSUE THREAD

**Issue by mozcelikors** [notro/fbtft#521]
Hi,
First, thanks for your incredibly helpful contributions. 

I am trying to initialize fbtft at very early run levels. For this purpose, I use psplash and I modify its script in order to issue modprobe commands.

The script has following commands:
```
modprobe spidev 2> /dev/kmsg
modprobe spi-bcm2835 2> /dev/kmsg
modprobe fbtft 2> /dev/kmsg
modprobe fbtft_device custom name=fb_ili9341 gpios=reset:25,dc:24,led:18 speed=16000000 rotate=270 bgr=1 2> /dev/kmsg
```
The script is experimental at this point. Using fbtft_device alone gives "Wrong parameter", so I added a few more commands, which suddenly solved this error. Maybe it's because fbtft

dmesg gives the following:
```

[    2.307353] fbtft: module is from the staging directory, the quality is unknown, you have been warned.
[    2.341755] fbtft_device: module is from the staging directory, the quality is unknown, you have been warned.
[    2.343497] spi spi0.1: ads7846 spi0.1 2000kHz 8 bits mode=0x00
[    2.343536] spi spi0.0: ili9341 spi0.0 16000kHz 8 bits mode=0x00
[    2.343612] bcm2708_fb soc:fb: soc:fb id=-1 pdata? no
[    2.343674] spi spi0.0: Deleting spi0.0
[    2.344410] fbtft_device: GPIOS used by 'fb_ili9341':
[    2.344437] fbtft_device: 'reset' = GPIO25
[    2.344452] fbtft_device: 'dc' = GPIO24
[    2.344465] fbtft_device: 'led' = GPIO18
[    2.344490] spi spi0.1: ads7846 spi0.1 2000kHz 8 bits mode=0x00
[    2.344513] spi spi0.0: fb_ili9341 spi0.0 16000kHz 8 bits mode=0x00
[    3.117103] udevd[134]: starting version 3.2.2
[    3.263392] udevd[135]: starting eudev-3.2.2
[    3.856876] gpiomem-bcm2835 20200000.gpiomem: Initialised: Registers at 0x20200000
[    3.894246] fb_ili9341: module is from the staging directory, the quality is unknown, you have been warned.
[    4.463207] brcmfmac: F1 signature read @0x18000000=0x1541a9a6
[    4.483969] usbcore: registered new interface driver brcmfmac
[    4.756487] asix 1-1.1:1.0 eth0: register 'asix' at usb-20980000.usb-1.1, ASIX AX88772B USB 2.0 Ethernet, 9c:eb:e8:0b:b9:e6
[    4.760345] usbcore: registered new interface driver asix
[    4.829198] brcmfmac: Firmware version = wl0: Aug  7 2017 00:46:29 version 7.45.41.46 (r666254 CY) FWID 01-f8a78378
[    4.830808] brcmfmac: brcmf_c_preinit_dcmds: CLM version = API: 12.2 Data: 7.11.15 Compiler: 1.24.2 ClmImport: 1.24.1 Creation: 2014-05-26 10:53:55 Inc Data: 9.10.41 Inc Compiler: 1.29.4 Inc ClmImport: 1.36.3 Creation: 2017-08-07 00:37:47 
[    5.625234] graphics fb1: fb_ili9341 frame buffer, 320x240, 150 KiB video memory, 16 KiB DMA buffer memory, fps=20, spi0.0 at 16 MHz
[    5.625746] spi0.1 supply vcc not found, using dummy regulator
[    5.631754] ads7846 spi0.1: touchscreen, irq 186
[    5.632583] input: ADS7846 Touchscreen as /devices/platform/soc/20204000.spi/spi_master/spi0/spi0.1/input/input0
```
I also added a device tree overlay with rpi-display.dtbo. So there are two things right now trying to initialize the fbtft module. My goal is to make this initialization earliest possible, before the init script finishes.

1. device tree overlay
2. init script from psplash

Now I'll try to explain what's happening in dmesg if I can:

1. seconds [2.3] : init script starts running, although output looks promising, I don't see anything on the TFT display, no backlight. I don't understand why.
2. seconds [3.89] : Here, we see again fb_ili9341 warning. Maybe this is because the device tree overlay is loaded around this time.
3. seconds [5.62] : The display is lit right now along with touchscreen stuff being loaded. This is definitely because of the device tree overlay, since I do not explicitly start touchscreen driver. However, I don't know why it took so long. I want to know why it did not start after the modprobe command in the init script. If I make the init script wait for /dev/fb1, then it waits forever.

There are probably some initializations/module loading I've forgotten that causes this problem. Since I'm trying to do this in very early in the boot process, I would expect this. I would like to know what else should be loaded, or which parameters?

Questions:

I would like to humbly ask for your guidance regarding the following questions

1. Is there a way to make the graphics load after the fbtft driver is loaded? 
2. I'm sure I have some configuration mistakes in the script above. Which parameters / commands should I change? What could I try there?

Many thanks..

**Comment by notro** [comment]
> The script is experimental at this point. Using fbtft_device alone gives "Wrong parameter", so I added a few more commands, which suddenly solved this error.

In order to use fbtft_device, the spi bus that you add a device for needs to be present. Meaning, you have to load spi_bcm2835 first.

Loading an overlay does the same as using fbtft_device, it adds a spi_device eventually.

This shows which spi devices the system has:
```
$ ls -l /sys/bus/spi/devices/
total 0
lrwxrwxrwx 1 root root 0 May 23 08:38 spi0.0 -> ../../../devices/platform/soc/20204000.spi/spi_master/spi0/spi0.0
lrwxrwxrwx 1 root root 0 May 23 08:38 spi0.1 -> ../../../devices/platform/soc/20204000.spi/spi_master/spi0/spi0.1

```

This shows my spi devices added through DT with the spidev node disabled (ie. not added):
```
$ ls -l /sys/firmware/devicetree/base/soc/spi@7e204000/
total 0
-r--r--r-- 1 root root  4 May 25 11:26 #address-cells
-r--r--r-- 1 root root  8 May 25 11:26 clocks
-r--r--r-- 1 root root 17 May 25 11:26 compatible
-r--r--r-- 1 root root  6 May 25 11:26 dma-names
-r--r--r-- 1 root root 16 May 25 11:26 dmas
-r--r--r-- 1 root root  8 May 25 11:26 interrupts
-r--r--r-- 1 root root  4 May 25 11:26 name
-r--r--r-- 1 root root  4 May 25 11:26 phandle
-r--r--r-- 1 root root  8 May 25 11:26 reg
drwxr-xr-x 2 root root  0 May 25 11:26 rpi-display@0
drwxr-xr-x 2 root root  0 May 25 11:26 rpi-display-ts@1
-r--r--r-- 1 root root  4 May 25 11:26 #size-cells
drwxr-xr-x 2 root root  0 May 25 11:26 spidev@0
drwxr-xr-x 2 root root  0 May 25 11:26 spidev@1
-r--r--r-- 1 root root  5 May 25 11:26 status
$ cat /sys/firmware/devicetree/base/soc/spi@7e204000/spidev@0/status
disabled
```

It could be that DT overlays won't work with Yocto. If it uses U-boot as boot loader, it probably isn't supported.

A Device Tree overlay is merged to the DTB by the Pi firmware and handed over to the Linux kernel, or U-boot if that's the bootloader. But I haven't heard of U-boot using that DTB, it does it's own DTB loading from the boot partition.

So there are 3 ways to add a fbtft spi device:
- fbtft_device, the spi bus has to be present
- Device Tree overlay, the bootloader needs to support it. The spi controller driver will turn the DT node into a spi_device when it registers.
- Add the nodes to the Device Tree source file and compile a new DTB: https://www.raspberrypi.org/documentation/configuration/device-tree.md

Two ways to load early:
1. Build your own kernel and make the required modules builtin: spi_bcm2835, fbtft, fbtft_device (unless DT overlay), fb_ili9341
  This shows that the driver is builtin, it would say ```=m``` if it was loadable:
```
$ zgrep SPI_BCM2835 /proc/config.gz
CONFIG_SPI_BCM2835=y
```

2. Use initramfs which is early userspace that is often used to load disk drivers. I haven't tried it in a long time: https://github.com/notro/fbtft/wiki/Bootsplash
