### ISSUE TITLE
ERROR: "fbtft_write_buf_dc" [drivers/staging/fbtft/fb_sh1106.ko] undefined!

### ISSUE THREAD

**Issue by vinayprydotinfotech** [notro/fbtft#556]
![err](https://user-images.githubusercontent.com/45288623/83786225-0f567280-a6b0-11ea-89f5-3b5355606e70.jpg)

hi guys can anyone help ? environment here is rpi-4.19.y raspberry kernel and raspberry pi 4 gcc8.3.0
i am getting this when adding tbtft

**Comment by neilabdev** [comment]
FYI, in my case while using BuildRoot,  I believe the reason for this is that FBTFT is now included in linux kernel 4x and above. Thus, selecting FBTFT kernel extension, which includes package FBTFT by default, would cause the error to occur. 

```
2015-01-19
The FBTFT drivers are now in the Linux kernel staging tree: https://git.kernel.org/cgit/linux/kernel/git/gregkh/staging.git/tree/drivers/staging/fbtft?h=staging-testing
Development in this github repo has ceased.
```
 https://github.com/notro/fbtft
