### ISSUE TITLE
Used the deprecated fbtft flex to view desktop on a Round Screen (240x240, GC9A01 Controller) 

### ISSUE THREAD

**Issue by Shargil** [notro/fbtft#574]
I finally found a solution and wrote it down!
www.instructables.com/Connected-Round-Screen-240x240-GC9A01-Controller-t/

**Comment by notro** [comment]
I've added a Device Tree overlay howto if you want to go that route (GC9A01 is MIPI DBI compatible): https://github.com/notro/fbtft/wiki/FBTFT-RPI-overlays
