### ISSUE TITLE
A request to take a look at this tinydrm patch

### ISSUE THREAD

**Issue by t123yh** [notro/fbtft#587]
Hi Notro,

I submitted this patch to kernel mailing list a month ago, but no one is replying me. It's a bug fix to tinydrm SPI, which would cause SPI transfers to be rejected on Rockchip platforms. Could you please take a look?

https://lore.kernel.org/lkml/20220308015611.3007395-1-t123yh.xyz@gmail.com/T/

**Comment by notro** [comment]
I had missed that patch, replied now.

**Comment by t123yh** [comment]
Hi @notro ,

I just sent a modified version of this patch, but your email server thinks my email is a spam.

```
550 5.7.2 Message content rejected (spam)
```

Could you please add a whitelist for my email address?

**Comment by notro** [comment]
> Could you please add a whitelist for my email address?

I have no control over the email server, so I can't do anything about it.

Found your patch here:
https://lore.kernel.org/dri-devel/20220510030219.2486687-1-t123yh.xyz@gmail.com/

Looks good at first glance, I'll test it and then apply it when I have some time.
