### ISSUE TITLE
support for ssd_1305

### ISSUE THREAD

**Issue by anshulmakkar** [notro/fbtft#594]
I couldn't find the driver for ssd1305. Has its support been dropped ?

**Comment by notro** [comment]
It's in mainline Linux: https://elixir.bootlin.com/linux/latest/source/drivers/staging/fbtft/fb_ssd1305.c

**Comment by tomsn1978** [comment]
Hello I want to initialize the screen to black when I boot the kernel，Where should I modify the source code

**Comment by anshulmakkar** [comment]
got you. thanks..
Won't it be useful to have the following initialization for CS and DS line in the init function:
```diff
+++ b/drivers/staging/fbtft/fb_ssd1305.c
@@ -43,6 +43,8 @@ static int init_display(struct fbtft_par *par)
                mutex_unlock(&par->gamma.lock);
        }

+       par->gpio.reset = 1;
+       par->gpio.dc = 0;
        /* Set Display OFF */
        write_reg(par, 0xAE);
```

**Comment by notro** [comment]
'reset' and 'dc' are pointers to [struct gpio_desc](https://elixir.bootlin.com/linux/latest/C/ident/gpio_desc) so this won't work ([struct fbtft_par](https://elixir.bootlin.com/linux/latest/C/ident/fbtft_par)).

Why do you want to do this?

**Comment by anshulmakkar** [comment]
The issue can be closed.
