### ISSUE TITLE
ILI9320 vs ILI9341

### ISSUE THREAD

**Issue by tinogoehlert** [notro/fbtft#6]
Hello, i've received an LCD driven by an ILI9320. Is this IC compatible to the ILI9341 your project already supports? if not, i would like to take care of that one and contribute it to your project.

**Comment by nagheid** [comment]
I am facing a similar issue with the Adafruit 2.8" (ILI9341). The screen is completely white. I followed the debug steps above but don't have a "Device code" value:

$ sudo modprobe --first-time fbtft_device name=adafruit28 gpios=reset:23,dc:18 debug=3

$ dmesg
[  925.566958] fbtft_device:  SPI devices registered:
[  925.567009] fbtft_device:      spidev spi0.1 64000kHz 8 bits mode=0x00
[  925.567025] fbtft_device:  'fb' Platform devices registered:
[  925.567080] fbtft_device:      bcm2708_fb id=-1 pdata? no
[  925.570520] fbtft_device:  GPIOS used by 'adafruit28':
[  925.570564] fbtft_device:    'reset' = GPIO23
[  925.570580] fbtft_device:    'dc' = GPIO18
[  925.570591] fbtft_device:  SPI devices registered:
[  925.570609] fbtft_device:      spidev spi0.1 64000kHz 8 bits mode=0x00
[  925.570627] fbtft_device:      fb_ili9341 spi0.0 32000kHz 8 bits mode=0x00
[  925.604261] fb_ili9341: module is from the staging directory, the quality is unknown, you have been warned.
[  925.607623] fb_ili9341 spi0.0: fbtft_gamma_parse_str() str=
[  925.607672] fb_ili9341 spi0.0: 1F 1A 18 0A 0F 06 45 87 32 0A 07 02 07 05 00
[  925.607672] 00 25 27 05 10 09 3A 78 4D 05 18 0D 38 3A 1F
[  925.607794] fb_ili9341 spi0.0: fbtft_request_gpios: 'reset' = GPIO23
[  925.607839] fb_ili9341 spi0.0: fbtft_request_gpios: 'dc' = GPIO18
[  925.607862] fb_ili9341 spi0.0: fbtft_verify_gpios()
[  925.607880] fb_ili9341 spi0.0: init_display()
[  925.607898] fb_ili9341 spi0.0: fbtft_reset()
[  925.856616] fb_ili9341 spi0.0: set_var()
[  925.925610] fb_ili9341 spi0.0: Display update: 2182 kB/s (68.724 ms), fps=0 (0.000 ms)
[  925.925652] fb_ili9341 spi0.0: set_gamma()
[  925.925909] fb_ili9341 spi0.0: fbtft_register_backlight()
[  925.925938] fb_ili9341 spi0.0: fbtft_register_backlight(): led pin not set, exiting.
[  925.927025] graphics fb1: fb_ili9341 frame buffer, 240x320, 150 KiB video memory, 16 KiB DMA buffer memory, fps=20, spi0.0 at 32 MHz

Your help will be greatly appreciated!

**Comment by notro** [comment]
If you have this: https://www.adafruit.com/product/1601
you should use name=pitft

**Comment by nagheid** [comment]
I have this: https://www.adafruit.com/products/1770

**Comment by notro** [comment]
Ok, the name is correct then.
White display means that the display controller isn't initialized. In this case probably because of miswiring unless Adafruit has changed the controller/panel.

This is the default pin assignments:
```
					{ "reset", 25 },
					{ "dc", 24 },
					{ "led", 18 },
```
https://github.com/raspberrypi/linux/blob/rpi-3.18.y/drivers/staging/fbtft/fbtft_device.c#L262

**Comment by nagheid** [comment]
I followed this for the wiring: https://learn.adafruit.com/user-space-spi-tft-python-library-ili9341-2-8/wiring 

So that's why I set custom gpios value in my command:
$ sudo modprobe --first-time fbtft_device name=adafruit28 **gpios=reset:23,dc:18** debug=3

Not sure about an led pin though as the adafruit wiring guide (linked above) didn't require such connection. So I left that empty

And I read on another issue that setting speed to 32000000 caused come problem so I tried with speed 16000000 but no luck

Any ideas on further debugging?

**Comment by notro** [comment]
@DougieLawson have you tried this display lately?

**Comment by DougieLawson** [comment]
It's tomorrow's project. Today I'm building a kernel to get my Wolfson audio card running on a B rev2 with the 3.18 kernel.

**Comment by nagheid** [comment]
Meanwhile, I'll try rewiring the DC and RST pins to the fbtft defaults and test again. Will keep you posted.

**Comment by DougieLawson** [comment]
@notro I downloaded the latest 3.18.11+-v7 kernel and tried this on my 2B.

config.txt has
```dtparam=spi=on
dtparam=i2c_arm=on
max_usb_current=1
gpu_mem=128
start_x=1
dtoverlay=rpi-display,rotate=90```

I wired it with lite==GPIO18, DC==gpio23 RST==gpio24 

Tested with con2fbmap and FRAMEBUFFER=/dev/fb1 startx and it worked perfectly.

**Comment by notro** [comment]
Thanks Dougie. That was clever using the rpi-display overlay.

**Comment by DougieLawson** [comment]
I read the code and that overlay was the closest match. It's the one I'd have used as a template if I'd needed to make my own overlay. I think I understand this DT and overlay stuff now.

**Comment by notro** [comment]
And suddenly it dawned on me: This will load an ads7846 device as well...
Probably not a big deal unless spi0.1 is needed.
The ads7846 driver doesn't check to see if anything is connected, so probing will succeed and it sets up an interrupt on gpio25.
cat /proc/interrupts will show if any interrupts are triggered, but I don't think it will.

**Comment by DougieLawson** [comment]
```
root@eagle ~ # cat /proc/interrupts
           CPU0       CPU1       CPU2       CPU3
 16:          0          0          0          0   ARMCTRL  16  bcm2708_fb dma
 24:       6471          0          0          0   ARMCTRL  24  DMA IRQ
 25:       2827          0          0          0   ARMCTRL  25  DMA IRQ
 32:    1549059          0          0          0   ARMCTRL  32  dwc_otg, dwc_otg_pcd, dwc_otg_hcd:usb1
 49:          0          0          0          0   ARMCTRL  49  3f200000.gpio:bank0
 50:          0          0          0          0   ARMCTRL  50  3f200000.gpio:bank1
 65:         18          0          0          0   ARMCTRL  65  ARM Mailbox IRQ
 66:     498274          0          0          0   ARMCTRL  66  VCHIQ doorbell
 75:          1          0          0          0   ARMCTRL  75
 79:          0          0          0          0   ARMCTRL  79  3f804000.i2c
 80: 2524810498          0          0          0   ARMCTRL  80  3f204000.spi
 84:      54932          0          0          0   ARMCTRL  84  mmc0
 99:    1018276     315120     312999      51354   ARMCTRL  99  arch_timer
505:          0          0          0          0  pinctrl-bcm2835  25  ads7846
FIQ:              usb_fiq
IPI0:          0          0          0          0  CPU wakeup interrupts
IPI1:          0          0          0          0  Timer broadcast interrupts
IPI2:    1966358   18894542   16494151    7862332  Rescheduling interrupts
IPI3:          7         11          8          8  Function call interrupts
IPI4:          1          5          0          0  Single function call interrupts
IPI5:          0          0          0          0  CPU stop interrupts
IPI6:          0          0          0          0  IRQ work interrupts
IPI7:          0          0          0          0  completion interrupts
Err:          0
root@eagle ~ #
```

Do we need a new DT overlay?

**Comment by notro** [comment]
There's no interrupt triggered, so as long as the pin is floating the driver just sits idle. But it's not desirable to have such a setup.

> Do we need a new DT overlay?

I have only made overlays for Pi display HATs/shields that I have and none of the other displays.
If I were to use a display that doesn't have an overlay, I would use fbtft_device.

/boot/config.txt
```
dtparam=spi=on
```

/etc/modules
```
fbtft_device name=adafruit28 gpios=reset:24,dc:23,led:18
```
