### ISSUE TITLE
Can the fbtft driver still be used directly with Raspberry Pi 5B?

### ISSUE THREAD

**Issue by jieweizero** [notro/fbtft#601]
Now the Raspberry Pi has been updated to 5B. The previously configured SPI display on 4B cannot be used on 5B. When manually entering the "fbcp" command, the error "pi@raspberrypi:~ $ fbcp * failed to open vchiq instance" is displayed. To adapt to Raspberry Pi 5B, do you need to modify the fbtft driver? What specific changes need to be made?

**Comment by notro** [comment]
> failed to open vchiq instance

[fbcp](https://github.com/tasanakorn/rpi-fbcp) uses dispmanx to copy the firmware framebuffer to fbtft. dispmanx is not supported on pi5: https://forums.raspberrypi.com/viewtopic.php?p=2138929#p2138929
