### ISSUE TITLE
X windows doesn't work on 2013-12-20-wheezy-raspbian

### ISSUE THREAD

**Issue by notro** [notro/fbtft#63]
This doesn't work on 2013-12-20-wheezy-raspbian:
```text
FRAMEBUFFER=/dev/fb1 startx
```

Solution:
Disable option in /usr/share/X11/xorg.conf.d/99-fbturbo.conf
```text
#        Option          "fbdev" "/dev/fb0"
```

Ref: http://www.raspberrypi.org/phpBB3/viewtopic.php?p=476459#p476459

**Comment by pilhuhn** [comment]
Isn't `/usr/share/X11/xorg.conf.d/99-fbturbo.conf`only a template file and the real one lives under `/etc/X11/`
