### ISSUE TITLE
Cannot load itdb28fb

### ISSUE THREAD

**Issue by Ianvdl** [notro/fbtft#67]
Hi Notro

Sorry if this is a noob mistake, but I'm having trouble with the itdb28fb driver.

I'm currently using the configuration as in the following thread: http://www.raspberrypi.org/phpBB3/viewtopic.php?f=64&t=43702

With a 2.4" display (not the 2.8" one). I successfully ran the demo code posted here: http://blog.iteadstudio.com/raspberry-pi-with-tft-lcd-demo/

And now I'd like to use your drivers so that I can have a working framebuffer or console output.

Here's my update output:

root@raspberrypi:/home/pi/RPILCD/RPILCD# sudo REPO_URI=https://github.com/notro/rpi-firmware rpi-update
 **\* Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS
 **\* Performing self-update
--2014-01-12 18:01:13--  https://github.com/Hexxeh/rpi-update/raw/master/rpi-update
Resolving github.com (github.com)... 192.30.252.131
Connecting to github.com (github.com)|192.30.252.131|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.github.com/Hexxeh/rpi-update/master/rpi-update [following]
--2014-01-12 18:01:23--  https://raw.github.com/Hexxeh/rpi-update/master/rpi-update
Resolving raw.github.com (raw.github.com)... 185.31.19.133
Connecting to raw.github.com (raw.github.com)|185.31.19.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7174 (7.0K) [text/plain]
Saving to: `/usr/bin/rpi-update.tmp'

100%[=======================================================================================================================================>] 7,174       --.-K/s   in 0.03s

2014-01-12 18:01:31 (226 KB/s) - `/usr/bin/rpi-update.tmp' saved [7174/7174]

 **\* Relaunching after update
 **\* Raspberry Pi firmware updater by Hexxeh, enhanced by AndrewS
 **\* ARM/GPU split is now defined in /boot/config.txt using the gpu_mem option!
 **\* Your firmware is already up to date

And this is what happens when I try to load the driver:

root@raspberrypi:/home/pi/RPILCD/RPILCD# sudo modprobe fbtft_device name=itdb28fb
ERROR: could not insert 'fbtft_device': Invalid argument

I can load any other driver, for example, I can load the ada driver as in the example on the home page perfectly, but obviously that won't work for this display.

Thank you in advance, I appreciate your work.

P.S. This is the display I purchased, the datasheets are in the "Documents" tab: http://netram.co.za/1421-24-tft-lcd-module-non-touch.html

**Comment by nicolaskrieger** [comment]
Hi,

I have the same lcd screen. Itead says it uses Ili9325 but the documentation says it uses S6D1121 controller.

This is the comand line I use :

sudo modprobe fbtft_device name=itdb24 gpios=db0:17,db1:18,db2:27,db3:22,db4:23,db5:24,db6:25,db7:4,cs:8,dc:2,wr:3,reset:7 rotate=90

And then : 
FRAMEBUFFER=/dev/fb1 startx 

I write it because it was hard to find it on internet. It may be usefull here
